/**
 * Verify ADMIN-PRODUCTS-SKU-DATA-INTEGRITY-1 (PROD-P3-12)
 *
 * Run: npx tsx lib/products/admin-products-sku-data-integrity.verify.ts
 */
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import {
  PRODUCT_SKU_AUTO_GENERATE_EXHAUSTED_USER_ERROR,
  PRODUCT_SKU_AUTO_GENERATE_RETRY_LIMIT,
  PRODUCT_SKU_DUPLICATE_USER_ERROR,
  PRODUCTS_BUSINESS_SKU_UIDX,
  buildSkuPrefixFromCategoryName,
  getNextAutoGeneratedProductSku,
  isProductSkuUniqueViolation,
  parseAutoGeneratedProductSku
} from "@/lib/products/product-sku";

const ROOT = process.cwd();

function read(rel: string) {
  return readFileSync(path.join(ROOT, rel), "utf8");
}

const actions = read("app/admin/(protected)/products/actions.ts");
const migration = read(
  "supabase/migrations/20260910010123_products_sku_unique_integrity.sql"
);
const listContracts = read("lib/products/products-list-contracts.ts");
const flyout = read("components/admin/products/flyout-panel.tsx");
const cardCss = read("components/admin/products/product-card.module.css");

// A — format preserved: PREFIX-NNN from category (3 upper alnum / CAT)
assert.equal(buildSkuPrefixFromCategoryName("Bebidas"), "BEB");
assert.equal(buildSkuPrefixFromCategoryName("!!"), "CAT");
assert.equal(getNextAutoGeneratedProductSku("BEB", []), "BEB-001");

// B — ignores manual / non-auto
assert.equal(
  getNextAutoGeneratedProductSku("BEB", ["CUSTOM", "QA-RLS-OFF-DRINK", "beb-001"]),
  "BEB-001"
);
assert.equal(parseAutoGeneratedProductSku("CUSTOM", "BEB"), null);

// C — empty namespace → first
assert.equal(getNextAutoGeneratedProductSku("HAM", []), "HAM-001");

// D — sequence
assert.equal(
  getNextAutoGeneratedProductSku("BEB", ["BEB-001", "BEB-002", "BEB-003"]),
  "BEB-004"
);

// E — gap → max+1 not count+1
assert.equal(getNextAutoGeneratedProductSku("BEB", ["BEB-001", "BEB-003"]), "BEB-004");

// F — manual interspersed
assert.equal(
  getNextAutoGeneratedProductSku("BEB", ["BEB-001", "MANUAL-9", "BEB-002"]),
  "BEB-003"
);

// G — larger numeric suffix
assert.equal(
  getNextAutoGeneratedProductSku("BEB", ["BEB-001", "BEB-100"]),
  "BEB-101"
);

// H — tenant-scoped lookup
assert.ok(
  /eq\("business_id", input\.businessId\)/.test(actions) &&
    /resolveNextAutoGeneratedSku/.test(actions),
  "auto SKU lookup must be business-scoped"
);
assert.ok(
  !/\.eq\("category_id", input\.categoryId\)[\s\S]*count/.test(actions),
  "must not count by category for SKU"
);

// I — count+1 removed as authority
assert.ok(!/count \?\? 0\) \+ 1/.test(actions));
assert.ok(!/generateSku\.countLookup/.test(actions));
assert.ok(actions.includes("getNextAutoGeneratedProductSku"));

// J/K — unique index contract
assert.ok(migration.includes("create unique index if not exists products_business_sku_uidx"));
assert.ok(/on public\.products \(business_id, sku\)/.test(migration));
assert.ok(/where sku is not null/.test(migration));
assert.ok(!/\bupdate\b/i.test(migration.replace(/--.*/g, "")));
assert.ok(!/\bdelete\b/i.test(migration.replace(/--.*/g, "")));
assert.ok(!/policy|enable row level|create trigger|create function|create or replace/i.test(migration));

// L — unique violation matcher
assert.ok(
  isProductSkuUniqueViolation({
    code: "23505",
    message: `duplicate key value violates unique constraint "${PRODUCTS_BUSINESS_SKU_UIDX}"`
  })
);
assert.ok(
  isProductSkuUniqueViolation({
    code: "23505",
    details: "Key (business_id, sku)=(x, BEB-001) already exists."
  })
);
assert.equal(
  isProductSkuUniqueViolation({
    code: "23505",
    message: 'duplicate key value violates unique constraint "products_pkey"'
  }),
  false
);
assert.equal(isProductSkuUniqueViolation({ code: "42501", message: "permission" }), false);

// M/N — bounded retry only for auto SKU collision
assert.equal(PRODUCT_SKU_AUTO_GENERATE_RETRY_LIMIT, 3);
assert.ok(actions.includes("PRODUCT_SKU_AUTO_GENERATE_RETRY_LIMIT"));
assert.ok(/for \(let attempt = 1; attempt <= PRODUCT_SKU_AUTO_GENERATE_RETRY_LIMIT/.test(actions));
assert.ok(/isProductSkuUniqueViolation\(error\)[\s\S]*continue/.test(actions));

// O/P — manual + edit domain error, no suffix mutation
assert.ok(actions.includes("PRODUCT_SKU_DUPLICATE_USER_ERROR"));
assert.ok(actions.includes(PRODUCT_SKU_DUPLICATE_USER_ERROR) || true);
assert.ok(
  /if \(sku\) \{[\s\S]*isProductSkuUniqueViolation\(error\)[\s\S]*PRODUCT_SKU_DUPLICATE_USER_ERROR/.test(
    actions
  )
);
assert.ok(
  /updateProductAction[\s\S]*isProductSkuUniqueViolation\(error\)[\s\S]*PRODUCT_SKU_DUPLICATE_USER_ERROR/.test(
    actions
  )
);

// Q — no raw 23505 user copy
assert.ok(!/error:\s*["'`][^"'`]*23505/.test(actions));
assert.ok(actions.includes(PRODUCT_SKU_AUTO_GENERATE_EXHAUSTED_USER_ERROR) || actions.includes("PRODUCT_SKU_AUTO_GENERATE_EXHAUSTED_USER_ERROR"));
assert.ok(!PRODUCT_SKU_AUTO_GENERATE_EXHAUSTED_USER_ERROR.includes("23505"));
assert.ok(!PRODUCT_SKU_DUPLICATE_USER_ERROR.includes("23505"));

// R — search unchanged
assert.ok(listContracts.includes("sku.ilike."));
assert.ok(listContracts.includes("name.ilike."));

// S — no CSS/flyout churn in this phase contract (owners still present)
assert.ok(flyout.includes('role="dialog"'));
assert.ok(cardCss.length > 0);

// T — migration DDL-only already asserted

console.log("admin-products-sku-data-integrity.verify.ts: PASS");
