/**
 * Product SKU format helpers (pure).
 * Auto format: `{PREFIX}-{NNN+}` where PREFIX is 1–3 uppercase alphanumerics
 * derived from category name (fallback `CAT`), and NNN is zero-padded to ≥3 digits.
 */

export const PRODUCTS_BUSINESS_SKU_UIDX = "products_business_sku_uidx";

export const PRODUCT_SKU_AUTO_GENERATE_RETRY_LIMIT = 3;

export const PRODUCT_SKU_DUPLICATE_USER_ERROR = "Ya existe un producto con ese SKU.";

export const PRODUCT_SKU_AUTO_GENERATE_EXHAUSTED_USER_ERROR =
  "No pudimos generar un SKU único. Intentá nuevamente.";

export function buildSkuPrefixFromCategoryName(categoryName: string) {
  const normalized = categoryName
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-zA-Z0-9]/g, "")
    .toUpperCase();

  if (!normalized) {
    return "CAT";
  }

  return normalized.slice(0, 3);
}

export function formatAutoGeneratedProductSku(prefix: string, sequence: number) {
  const paddedNumber = String(sequence).padStart(3, "0");
  return `${prefix}-${paddedNumber}`;
}

export function parseAutoGeneratedProductSku(
  sku: string,
  prefix: string
): { sequence: number } | null {
  if (!prefix || !sku) {
    return null;
  }

  const escapedPrefix = prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = new RegExp(`^${escapedPrefix}-(\\d+)$`).exec(sku);

  if (!match) {
    return null;
  }

  const sequence = Number(match[1]);
  if (!Number.isFinite(sequence) || sequence < 1) {
    return null;
  }

  return { sequence };
}

export function getNextAutoGeneratedProductSku(
  prefix: string,
  existingSkus: ReadonlyArray<string | null | undefined>
) {
  let maxSequence = 0;

  for (const sku of existingSkus) {
    if (typeof sku !== "string") {
      continue;
    }

    const parsed = parseAutoGeneratedProductSku(sku, prefix);
    if (!parsed) {
      continue;
    }

    if (parsed.sequence > maxSequence) {
      maxSequence = parsed.sequence;
    }
  }

  return formatAutoGeneratedProductSku(prefix, maxSequence + 1);
}

type UniqueViolationLike = {
  code?: unknown;
  message?: unknown;
  details?: unknown;
  hint?: unknown;
  constraint?: unknown;
};

function readErrorField(error: UniqueViolationLike, key: keyof UniqueViolationLike) {
  const value = error[key];
  return typeof value === "string" ? value : "";
}

export function isProductSkuUniqueViolation(error: unknown) {
  if (!error || typeof error !== "object") {
    return false;
  }

  const candidate = error as UniqueViolationLike;
  if (candidate.code !== "23505") {
    return false;
  }

  const haystack = [
    readErrorField(candidate, "message"),
    readErrorField(candidate, "details"),
    readErrorField(candidate, "hint"),
    readErrorField(candidate, "constraint")
  ]
    .join(" ")
    .toLowerCase();

  if (haystack.includes(PRODUCTS_BUSINESS_SKU_UIDX.toLowerCase())) {
    return true;
  }

  // PostgREST often surfaces the conflicting key columns without the index name.
  return (
    haystack.includes("(business_id, sku)") ||
    (haystack.includes("business_id") && haystack.includes("sku"))
  );
}
