"use server";

import { revalidatePath } from "next/cache";
import { getActionErrorMessage, logActionFailure } from "@/lib/admin/action-errors";
import { requireAdminPermission } from "@/lib/admin/context";
import { revalidatePublicCatalogCache } from "@/lib/catalog/public-cache-tags";
import { getAdminProductById, type AdminProduct } from "@/lib/products/admin";
import { canonicalizeIdSet } from "@/lib/products/edit-unified-draft";
import {
  resolveEffectiveProductAvailability,
  TRACKED_ZERO_STOCK_ENABLE_ERROR
} from "@/lib/products/products-stock-availability-contract";
import {
  PRODUCT_SKU_AUTO_GENERATE_EXHAUSTED_USER_ERROR,
  PRODUCT_SKU_AUTO_GENERATE_RETRY_LIMIT,
  PRODUCT_SKU_DUPLICATE_USER_ERROR,
  buildSkuPrefixFromCategoryName,
  getNextAutoGeneratedProductSku,
  isProductSkuUniqueViolation
} from "@/lib/products/product-sku";
import {
  getCanonicalProductImagePublicUrl,
  isCanonicalProductUuid,
  isOwnedProductImagePath,
  removeProductImageIfUnreferenced,
  type ProductImageIntent
} from "@/lib/products/product-image-storage";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type ActionState = {
  error?: string;
  success?: boolean;
  warning?: string;
};

type GetAdminProductActionResult = {
  product: AdminProduct | null;
  error?: string;
};

export async function getAdminProductByIdAction(
  productId: string
): Promise<GetAdminProductActionResult> {
  if (!productId) {
    return {
      product: null,
      error: "Falta identificar el producto."
    };
  }

  const adminContext = await requireAdminPermission("manageProducts");
  try {
    const product = await getAdminProductById(adminContext.businessId, productId);

    if (!product) {
      return {
        product: null,
        error: "No encontramos el producto o ya no pertenece a tu negocio."
      };
    }

    return { product };
  } catch (error) {
    logActionFailure("products.getById", error, { productId });
    return {
      product: null,
      error: getActionErrorMessage(error, "No pudimos cargar el producto.")
    };
  }
}

export async function cleanupPendingProductImageAction(
  imagePath: string
): Promise<ActionState> {
  const trimmedPath = imagePath.trim();
  if (!trimmedPath) {
    return { error: "Falta la ruta de imagen." };
  }

  const adminContext = await requireAdminPermission("manageProducts");
  try {
    if (
      !isOwnedProductImagePath(trimmedPath, adminContext.businessId, {
        requireCanonicalProductFolder: true
      })
    ) {
      return { error: "La imagen no pertenece a este negocio." };
    }

    const supabase = await createSupabaseServerClient();
    const status = await removeProductImageIfUnreferenced({
      supabase,
      businessId: adminContext.businessId,
      imageUrlOrPath: trimmedPath
    });

    if (status === "failed") {
      logActionFailure("products.cleanupPendingImage", new Error(status), {
        businessId: adminContext.businessId
      });
      return { error: "No pudimos limpiar la imagen temporal." };
    }

    return { success: true };
  } catch (error) {
    logActionFailure("products.cleanupPendingImage", error, {
      businessId: adminContext.businessId
    });
    return {
      error: getActionErrorMessage(error, "No pudimos limpiar la imagen temporal.")
    };
  }
}

export async function createProductAction(
  _prevState: ActionState,
  formData: FormData
) {
  const productId = getTrimmedString(formData.get("product_id"));
  const name = getTrimmedString(formData.get("name"));
  const price = getPriceValue(formData.get("price"));
  const description = getOptionalTrimmedString(formData.get("description"));
  const categoryId = getTrimmedString(formData.get("category_id"));
  const imageIntent = parseProductImageIntent(formData.get("image_intent"), [
    "none",
    "replace"
  ]);
  const imagePath = getOptionalTrimmedString(formData.get("image_path"));
  const sku = formData.get("sku")?.toString().trim() || null;
  const stockStr = formData.get("stock")?.toString();
  const stock = stockStr ? parseInt(stockStr, 10) : 0;
  const trackStock = formData.get("track_stock") === "on";

  if (!productId || !isCanonicalProductUuid(productId)) {
    return { error: "Identificador de producto inválido." };
  }

  if (!name) {
    return { error: "Ingresa un nombre para el producto." };
  }

  if (price === null) {
    return { error: "Ingresa un precio valido." };
  }

  if (!categoryId) {
    return { error: "Selecciona una categoria." };
  }

  if (!Number.isFinite(stock) || stock < 0) {
    return { error: "Ingresa un stock valido." };
  }

  if (!imageIntent) {
    return { error: "La intención de imagen no es válida." };
  }

  const adminContext = await requireAdminPermission("manageProducts");
  try {
    const supabase = await createSupabaseServerClient();

    const categoryValidationError = await validateCategoryOwnership({
      supabase,
      businessId: adminContext.businessId,
      categoryId
    });

    if (categoryValidationError) {
      return { error: categoryValidationError };
    }

    let resolvedImageUrl: string | null = null;

    if (imageIntent === "replace") {
      if (
        !imagePath ||
        !isOwnedProductImagePath(imagePath, adminContext.businessId, {
          requireCanonicalProductFolder: true
        })
      ) {
        return { error: "La imagen del producto no es válida." };
      }

      const pathParts = imagePath.split("/");
      if (pathParts[1] !== productId) {
        return { error: "La imagen del producto no es válida." };
      }

      resolvedImageUrl = getCanonicalProductImagePublicUrl(supabase, imagePath);
    }

    const effectiveIsAvailable = resolveEffectiveProductAvailability({
      trackStock,
      stock,
      requestedAvailable: true
    });

    const insertPayloadBase = {
      id: productId,
      business_id: adminContext.businessId,
      name,
      price,
      category_id: categoryId,
      description,
      image_url: resolvedImageUrl,
      is_available: effectiveIsAvailable,
      stock,
      track_stock: trackStock
    };

    if (sku) {
      const { error } = await supabase.from("products").insert({
        ...insertPayloadBase,
        sku
      });

      if (error) {
        if (isProductSkuUniqueViolation(error)) {
          return { error: PRODUCT_SKU_DUPLICATE_USER_ERROR };
        }

        throw new Error("No pudimos crear el producto.");
      }
    } else {
      const autoSkuPrefix = await resolveAutoSkuPrefixForCategory({
        supabase,
        businessId: adminContext.businessId,
        categoryId
      });

      if (autoSkuPrefix.error || !autoSkuPrefix.prefix) {
        return {
          error: autoSkuPrefix.error ?? "No pudimos generar el SKU automaticamente."
        };
      }

      let inserted = false;

      for (let attempt = 1; attempt <= PRODUCT_SKU_AUTO_GENERATE_RETRY_LIMIT; attempt += 1) {
        const candidateSku = await resolveNextAutoGeneratedSku({
          supabase,
          businessId: adminContext.businessId,
          prefix: autoSkuPrefix.prefix
        });

        if (candidateSku.error || !candidateSku.sku) {
          return {
            error: candidateSku.error ?? "No pudimos generar el SKU automaticamente."
          };
        }

        const { error } = await supabase.from("products").insert({
          ...insertPayloadBase,
          sku: candidateSku.sku
        });

        if (!error) {
          inserted = true;
          break;
        }

        if (isProductSkuUniqueViolation(error)) {
          continue;
        }

        throw new Error("No pudimos crear el producto.");
      }

      if (!inserted) {
        return { error: PRODUCT_SKU_AUTO_GENERATE_EXHAUSTED_USER_ERROR };
      }
    }

    revalidatePath("/admin/products");
    revalidatePublicCatalogCache({
      businessId: adminContext.businessId,
      slug: adminContext.businessSlug,
      scope: "catalog"
    });
    return { success: true };
  } catch (error) {
    logActionFailure("products.create", error, { categoryId, productId });
    return { error: getActionErrorMessage(error, "No pudimos crear el producto.") };
  }
}

export async function setProductAvailabilityAction(
  productId: string,
  isAvailable: boolean
): Promise<ActionState> {
  if (!productId) {
    return { error: "Falta identificar el producto." };
  }

  const adminContext = await requireAdminPermission("manageProducts");
  try {
    const supabase = await createSupabaseServerClient();

    const { data: currentProduct, error: currentProductError } = await supabase
      .from("products")
      .select("id, stock, track_stock, archived_at")
      .eq("id", productId)
      .eq("business_id", adminContext.businessId)
      .maybeSingle();

    if (currentProductError) {
      throw new Error("No pudimos cargar el producto.");
    }

    if (!currentProduct) {
      return { error: "Este producto ya no existe o pertenece a otro negocio." };
    }

    if (currentProduct.archived_at != null) {
      return {
        error: "El producto está archivado. Restáuralo para editarlo."
      };
    }

    if (
      isAvailable &&
      currentProduct.track_stock === true &&
      (currentProduct.stock ?? 0) <= 0
    ) {
      return { error: TRACKED_ZERO_STOCK_ENABLE_ERROR };
    }

    const { error } = await supabase
      .from("products")
      .update({ is_available: isAvailable })
      .eq("id", productId)
      .eq("business_id", adminContext.businessId);

    if (error) {
      throw new Error("No pudimos actualizar la disponibilidad del producto.");
    }

    revalidatePath("/admin/products");
    revalidatePublicCatalogCache({
      businessId: adminContext.businessId,
      slug: adminContext.businessSlug,
      scope: "catalog"
    });
    return { success: true };
  } catch (error) {
    logActionFailure("products.setAvailability", error, { productId, isAvailable });
    return {
      error: getActionErrorMessage(error, "No pudimos actualizar la disponibilidad del producto.")
    };
  }
}

// LEGACY — superseded for normal Edit by saveProductEditDraftAction; retained temporarily for verify/historical grep. Do not use for new Edit saves.
export async function updateProductAction(
  _prevState: ActionState,
  formData: FormData
) {
  const productId = getTrimmedString(formData.get("product_id"));
  const name = getTrimmedString(formData.get("name"));
  const price = getPriceValue(formData.get("price"));
  const description = getOptionalTrimmedString(formData.get("description"));
  const categoryId = getTrimmedString(formData.get("category_id"));
  const imageIntent = parseProductImageIntent(formData.get("image_intent"), [
    "keep",
    "replace",
    "remove"
  ]);
  const imagePath = getOptionalTrimmedString(formData.get("image_path"));
  const isAvailable = formData.get("is_available") === "on";
  const trackStock = formData.get("track_stock") === "on";
  const sku = formData.get("sku")?.toString().trim() || null;
  const stockStr = formData.get("stock")?.toString();
  const stock = stockStr ? parseInt(stockStr, 10) : 0;

  if (!productId) {
    return { error: "Falta identificar el producto." };
  }

  if (!name) {
    return { error: "Ingresa un nombre para el producto." };
  }

  if (price === null) {
    return { error: "Ingresa un precio valido." };
  }

  if (!categoryId) {
    return { error: "Selecciona una categoria." };
  }

  if (!Number.isFinite(stock) || stock < 0) {
    return { error: "Ingresa un stock valido." };
  }

  if (!imageIntent) {
    return { error: "La intención de imagen no es válida." };
  }

  const adminContext = await requireAdminPermission("manageProducts");
  try {
    const supabase = await createSupabaseServerClient();

    const categoryValidationError = await validateCategoryOwnership({
      supabase,
      businessId: adminContext.businessId,
      categoryId
    });

    if (categoryValidationError) {
      return { error: categoryValidationError };
    }

    const { data: currentProduct, error: currentProductError } = await supabase
      .from("products")
      .select("id, image_url, archived_at")
      .eq("id", productId)
      .eq("business_id", adminContext.businessId)
      .maybeSingle();

    if (currentProductError) {
      throw new Error("No pudimos cargar el producto.");
    }

    if (!currentProduct) {
      return { error: "Este producto ya no existe o pertenece a otro negocio." };
    }

    if (currentProduct.archived_at != null) {
      return {
        error: "El producto está archivado. Restáuralo para editarlo."
      };
    }

    const effectiveIsAvailable = resolveEffectiveProductAvailability({
      trackStock,
      stock,
      requestedAvailable: isAvailable
    });

    const updatePayload: {
      name: string;
      price: number;
      description: string | null;
      category_id: string;
      is_available: boolean;
      sku: string | null;
      stock: number;
      track_stock: boolean;
      image_url?: string | null;
    } = {
      name,
      price,
      description,
      category_id: categoryId,
      is_available: effectiveIsAvailable,
      sku,
      stock,
      track_stock: trackStock
    };

    const previousImageUrl: string | null = currentProduct.image_url ?? null;

    if (imageIntent === "replace") {
      if (
        !imagePath ||
        !isOwnedProductImagePath(imagePath, adminContext.businessId, {
          requireCanonicalProductFolder: true
        })
      ) {
        return { error: "La imagen del producto no es válida." };
      }

      const pathParts = imagePath.split("/");
      if (pathParts[1] !== productId) {
        return { error: "La imagen del producto no es válida." };
      }

      updatePayload.image_url = getCanonicalProductImagePublicUrl(supabase, imagePath);
    } else if (imageIntent === "remove") {
      updatePayload.image_url = null;
    }

    const { error } = await supabase
      .from("products")
      .update(updatePayload)
      .eq("id", productId)
      .eq("business_id", adminContext.businessId);

    if (error) {
      if (isProductSkuUniqueViolation(error)) {
        return { error: PRODUCT_SKU_DUPLICATE_USER_ERROR };
      }

      throw new Error("No pudimos actualizar el producto.");
    }

    if (
      (imageIntent === "replace" || imageIntent === "remove") &&
      previousImageUrl
    ) {
      const cleanupStatus = await removeProductImageIfUnreferenced({
        supabase,
        businessId: adminContext.businessId,
        imageUrlOrPath: previousImageUrl
      });

      if (cleanupStatus === "failed") {
        logActionFailure(
          "products.update.imageCleanup",
          new Error(cleanupStatus),
          { productId, businessId: adminContext.businessId }
        );
      }
    }

    revalidatePath("/admin/products");
    revalidatePublicCatalogCache({
      businessId: adminContext.businessId,
      slug: adminContext.businessSlug,
      scope: "catalog"
    });
    return { success: true };
  } catch (error) {
    logActionFailure("products.update", error, { productId, categoryId });
    return { error: getActionErrorMessage(error, "No pudimos actualizar el producto.") };
  }
}

export async function saveProductEditDraftAction(
  _prevState: ActionState,
  formData: FormData
) {
  const productId = getTrimmedString(formData.get("product_id"));
  const name = getTrimmedString(formData.get("name"));
  const price = getPriceValue(formData.get("price"));
  const description = getOptionalTrimmedString(formData.get("description"));
  const imageIntent = parseProductImageIntent(formData.get("image_intent"), [
    "keep",
    "replace",
    "remove"
  ]);
  const imagePath = getOptionalTrimmedString(formData.get("image_path"));
  const isAvailable = formData.get("is_available") === "on";
  const trackStock = formData.get("track_stock") === "on";
  const sku = formData.get("sku")?.toString().trim() || null;
  const stockStr = formData.get("stock")?.toString();
  const stock = stockStr ? parseInt(stockStr, 10) : 0;
  const hiddenGroupIds = parseHiddenIdList(formData, "hidden_group_ids");
  const hiddenOptionIds = parseHiddenIdList(formData, "hidden_option_ids");

  if (!productId) {
    return { error: "Falta identificar el producto." };
  }

  if (!name) {
    return { error: "Ingresa un nombre para el producto." };
  }

  if (price === null) {
    return { error: "Ingresa un precio valido." };
  }

  if (!Number.isFinite(stock) || stock < 0) {
    return { error: "Ingresa un stock valido." };
  }

  if (!imageIntent) {
    return { error: "La intención de imagen no es válida." };
  }

  const adminContext = await requireAdminPermission("manageProducts");
  try {
    const supabase = await createSupabaseServerClient();

    const { data: currentProduct, error: currentProductError } = await supabase
      .from("products")
      .select("id, image_url, archived_at")
      .eq("id", productId)
      .eq("business_id", adminContext.businessId)
      .maybeSingle();

    if (currentProductError) {
      throw new Error("No pudimos cargar el producto.");
    }

    if (!currentProduct) {
      return { error: "Este producto ya no existe o pertenece a otro negocio." };
    }

    if (currentProduct.archived_at != null) {
      return {
        error: "El producto está archivado. Restáuralo para editarlo."
      };
    }

    const previousImageUrl: string | null = currentProduct.image_url ?? null;

    let resolvedImageUrl: string | null = null;

    if (imageIntent === "replace") {
      if (
        !imagePath ||
        !isOwnedProductImagePath(imagePath, adminContext.businessId, {
          requireCanonicalProductFolder: true
        })
      ) {
        return { error: "La imagen del producto no es válida." };
      }

      const pathParts = imagePath.split("/");
      if (pathParts[1] !== productId) {
        return { error: "La imagen del producto no es válida." };
      }

      resolvedImageUrl = getCanonicalProductImagePublicUrl(supabase, imagePath);
    }

    const effectiveIsAvailable = resolveEffectiveProductAvailability({
      trackStock,
      stock,
      requestedAvailable: isAvailable
    });

    // Database types lag the live RPC; narrow cast on name/args only.
    const { error } = await (
      supabase.rpc as unknown as (
        fn: "save_product_edit_draft",
        args: {
          p_product_id: string;
          p_name: string;
          p_description: string | null;
          p_price: number;
          p_sku: string | null;
          p_stock: number;
          p_is_available: boolean;
          p_track_stock: boolean;
          p_image_intent: string;
          p_image_url: string | null;
          p_hidden_group_ids: string[];
          p_hidden_option_ids: string[];
        }
      ) => PromiseLike<{
        data: string | null;
        error: {
          message?: string;
          code?: string;
          details?: string;
          hint?: string;
        } | null;
      }>
    )("save_product_edit_draft", {
      p_product_id: productId,
      p_name: name,
      p_description: description,
      p_price: price,
      p_sku: sku,
      p_stock: stock,
      p_is_available: effectiveIsAvailable,
      p_track_stock: trackStock,
      p_image_intent: imageIntent,
      p_image_url: resolvedImageUrl,
      p_hidden_group_ids: hiddenGroupIds,
      p_hidden_option_ids: hiddenOptionIds
    });

    if (error) {
      if (isProductSkuUniqueViolation(error)) {
        return { error: PRODUCT_SKU_DUPLICATE_USER_ERROR };
      }

      const domainError = mapSaveProductEditDraftRpcError(error.message);
      if (domainError) {
        return { error: domainError };
      }

      throw new Error("No pudimos guardar el producto.");
    }

    if (
      (imageIntent === "replace" || imageIntent === "remove") &&
      previousImageUrl
    ) {
      const cleanupStatus = await removeProductImageIfUnreferenced({
        supabase,
        businessId: adminContext.businessId,
        imageUrlOrPath: previousImageUrl
      });

      if (cleanupStatus === "failed") {
        logActionFailure(
          "products.saveEditDraft.imageCleanup",
          new Error(cleanupStatus),
          { productId, businessId: adminContext.businessId }
        );
      }
    }

    revalidatePath("/admin/products");
    revalidatePath("/admin/products/customizations");
    revalidatePublicCatalogCache({
      businessId: adminContext.businessId,
      slug: adminContext.businessSlug,
      scope: "catalog"
    });
    revalidatePublicCatalogCache({
      businessId: adminContext.businessId,
      slug: adminContext.businessSlug,
      scope: "customization"
    });
    return { success: true };
  } catch (error) {
    logActionFailure("products.saveEditDraft", error, { productId });
    return { error: getActionErrorMessage(error, "No pudimos guardar el producto.") };
  }
}

type LifecycleActionState = {
  error?: string;
  success?: boolean;
  warning?: string;
};

function revalidateProductLifecycleCaches(input: {
  businessId: string;
  businessSlug: string | null;
  includeAdminCustomizations?: boolean;
}) {
  revalidatePath("/admin/products");
  if (input.includeAdminCustomizations) {
    revalidatePath("/admin/products/customizations");
  }
  revalidatePublicCatalogCache({
    businessId: input.businessId,
    slug: input.businessSlug,
    scope: "catalog"
  });
  revalidatePublicCatalogCache({
    businessId: input.businessId,
    slug: input.businessSlug,
    scope: "customization"
  });
}

export async function archiveProductAction(
  productId: string
): Promise<LifecycleActionState> {
  if (!productId || !isCanonicalProductUuid(productId)) {
    return { error: "Falta identificar el producto." };
  }

  const adminContext = await requireAdminPermission("manageProducts");
  try {
    const supabase = await createSupabaseServerClient();

    const { data: currentProduct, error: currentProductError } = await supabase
      .from("products")
      .select("id, archived_at")
      .eq("id", productId)
      .eq("business_id", adminContext.businessId)
      .maybeSingle();

    if (currentProductError) {
      throw new Error("No pudimos cargar el producto.");
    }

    if (!currentProduct) {
      return { error: "El producto ya está archivado o ya no está disponible." };
    }

    if (currentProduct.archived_at != null) {
      return { error: "El producto ya está archivado o ya no está disponible." };
    }

    const { data: updatedRows, error } = await supabase
      .from("products")
      .update({
        archived_at: new Date().toISOString(),
        is_available: false
      })
      .eq("id", productId)
      .eq("business_id", adminContext.businessId)
      .is("archived_at", null)
      .select("id");

    if (error) {
      throw new Error("No pudimos archivar el producto.");
    }

    if (!updatedRows || updatedRows.length === 0) {
      return { error: "El producto ya está archivado o ya no está disponible." };
    }

    revalidateProductLifecycleCaches({
      businessId: adminContext.businessId,
      businessSlug: adminContext.businessSlug
    });
    return { success: true };
  } catch (error) {
    logActionFailure("products.archive", error, { productId });
    return {
      error: getActionErrorMessage(
        error,
        "No pudimos completar la acción. Intentá nuevamente."
      )
    };
  }
}

export async function restoreProductAction(
  productId: string
): Promise<LifecycleActionState> {
  if (!productId || !isCanonicalProductUuid(productId)) {
    return { error: "Falta identificar el producto." };
  }

  const adminContext = await requireAdminPermission("manageProducts");
  try {
    const supabase = await createSupabaseServerClient();

    const { data: currentProduct, error: currentProductError } = await supabase
      .from("products")
      .select("id, archived_at")
      .eq("id", productId)
      .eq("business_id", adminContext.businessId)
      .maybeSingle();

    if (currentProductError) {
      throw new Error("No pudimos cargar el producto.");
    }

    if (!currentProduct) {
      return { error: "El producto ya fue restaurado o ya no existe." };
    }

    if (currentProduct.archived_at == null) {
      return { error: "El producto ya fue restaurado o ya no existe." };
    }

    const { data: updatedRows, error } = await supabase
      .from("products")
      .update({
        archived_at: null,
        is_available: false
      })
      .eq("id", productId)
      .eq("business_id", adminContext.businessId)
      .not("archived_at", "is", null)
      .select("id");

    if (error) {
      throw new Error("No pudimos restaurar el producto.");
    }

    if (!updatedRows || updatedRows.length === 0) {
      return { error: "El producto ya fue restaurado o ya no existe." };
    }

    revalidateProductLifecycleCaches({
      businessId: adminContext.businessId,
      businessSlug: adminContext.businessSlug
    });
    return { success: true };
  } catch (error) {
    logActionFailure("products.restore", error, { productId });
    return {
      error: getActionErrorMessage(
        error,
        "No pudimos completar la acción. Intentá nuevamente."
      )
    };
  }
}

export async function deleteProductPermanentlyAction(
  productId: string
): Promise<LifecycleActionState> {
  if (!productId || !isCanonicalProductUuid(productId)) {
    return { error: "Falta identificar el producto." };
  }

  const adminContext = await requireAdminPermission("manageProducts");
  try {
    const supabase = await createSupabaseServerClient();

    type DeleteProductPermanentlyRow = {
      deleted_product_id: string | null;
      image_url: string | null;
      deleted: boolean;
    };

    const { data, error } = await (
      supabase.rpc as unknown as (
        fn: "delete_product_permanently",
        args: { p_product_id: string }
      ) => PromiseLike<{
        data: DeleteProductPermanentlyRow[] | DeleteProductPermanentlyRow | null;
        error: { message?: string; code?: string } | null;
      }>
    )("delete_product_permanently", {
      p_product_id: productId
    });

    if (error) {
      throw new Error("No pudimos eliminar el producto.");
    }

    const row = Array.isArray(data) ? data[0] : data;
    const deleted = row?.deleted === true;

    if (!deleted) {
      return { error: "El producto ya no existe." };
    }

    const imageUrl = typeof row?.image_url === "string" ? row.image_url : null;
    let cleanupWarning: string | undefined;

    if (imageUrl) {
      const cleanupStatus = await removeProductImageIfUnreferenced({
        supabase,
        businessId: adminContext.businessId,
        imageUrlOrPath: imageUrl
      });

      if (cleanupStatus === "failed" || cleanupStatus === "skipped_invalid") {
        logActionFailure(
          "products.deletePermanently.imageCleanup",
          new Error(cleanupStatus),
          { productId, businessId: adminContext.businessId }
        );
        cleanupWarning =
          "Producto eliminado. No se pudo limpiar su imagen automáticamente.";
      }
    }

    revalidateProductLifecycleCaches({
      businessId: adminContext.businessId,
      businessSlug: adminContext.businessSlug,
      includeAdminCustomizations: true
    });

    return cleanupWarning
      ? { success: true, warning: cleanupWarning }
      : { success: true };
  } catch (error) {
    logActionFailure("products.deletePermanently", error, { productId });
    return {
      error: getActionErrorMessage(
        error,
        "No pudimos completar la acción. Intentá nuevamente."
      )
    };
  }
}

function parseHiddenIdList(formData: FormData, key: string) {
  const values: string[] = [];
  for (const entry of formData.getAll(key)) {
    if (typeof entry === "string") {
      values.push(entry);
    }
  }

  return canonicalizeIdSet(values).filter(isCanonicalProductUuid);
}

function mapSaveProductEditDraftRpcError(message: string | undefined) {
  if (!message || !message.includes("SAVE_PRODUCT_EDIT_DRAFT_")) {
    return null;
  }

  if (message.includes("SAVE_PRODUCT_EDIT_DRAFT_UNAUTHORIZED")) {
    return "Tu sesión no es válida. Volvé a iniciar sesión.";
  }

  if (message.includes("SAVE_PRODUCT_EDIT_DRAFT_FORBIDDEN")) {
    return "No tenés permiso para editar productos.";
  }

  if (message.includes("SAVE_PRODUCT_EDIT_DRAFT_PRODUCT_NOT_FOUND")) {
    return "Este producto ya no existe o pertenece a otro negocio.";
  }

  if (message.includes("SAVE_PRODUCT_EDIT_DRAFT_INVALID_GROUP")) {
    return "Alguno de los grupos ocultos no es válido para este producto.";
  }

  if (message.includes("SAVE_PRODUCT_EDIT_DRAFT_INVALID_OPTION")) {
    return "Alguna de las opciones ocultas no es válida para este producto.";
  }

  if (message.includes("SAVE_PRODUCT_EDIT_DRAFT_LEGACY_OVERRIDE_SHAPE")) {
    return "Hay personalizaciones incompatibles en este producto. Recargá e intentá nuevamente.";
  }

  if (message.includes("SAVE_PRODUCT_EDIT_DRAFT_INVALID_INPUT")) {
    return "Los datos del producto no son válidos.";
  }

  if (message.includes("SAVE_PRODUCT_EDIT_DRAFT_PRODUCT_UPDATE_FAILED")) {
    return "No pudimos guardar el producto.";
  }

  return "No pudimos guardar el producto.";
}

function parseProductImageIntent(
  value: FormDataEntryValue | null,
  allowed: readonly ProductImageIntent[]
): ProductImageIntent | null {
  if (typeof value !== "string") {
    return null;
  }

  const intent = value.trim() as ProductImageIntent;
  return allowed.includes(intent) ? intent : null;
}

function getTrimmedString(value: FormDataEntryValue | null) {
  return typeof value === "string" ? value.trim() : "";
}

function getOptionalTrimmedString(value: FormDataEntryValue | null) {
  const trimmedValue = getTrimmedString(value);
  return trimmedValue ? trimmedValue : null;
}

function getPriceValue(value: FormDataEntryValue | null) {
  if (typeof value !== "string") {
    return null;
  }

  const parsedValue = Number(value);

  if (!Number.isFinite(parsedValue) || parsedValue < 0) {
    return null;
  }

  return parsedValue;
}

async function resolveAutoSkuPrefixForCategory(input: {
  supabase: Awaited<ReturnType<typeof createSupabaseServerClient>>;
  businessId: string;
  categoryId: string;
}) {
  const { data: category, error: categoryError } = await input.supabase
    .from("categories")
    .select("name")
    .eq("id", input.categoryId)
    .eq("business_id", input.businessId)
    .single();

  if (categoryError || !category?.name) {
    logActionFailure("products.generateSku.categoryLookup", categoryError, {
      businessId: input.businessId,
      categoryId: input.categoryId
    });
    return { prefix: null, error: "No pudimos obtener la categoria para generar el SKU." };
  }

  return { prefix: buildSkuPrefixFromCategoryName(category.name) };
}

async function resolveNextAutoGeneratedSku(input: {
  supabase: Awaited<ReturnType<typeof createSupabaseServerClient>>;
  businessId: string;
  prefix: string;
}) {
  const { data, error } = await input.supabase
    .from("products")
    .select("sku")
    .eq("business_id", input.businessId)
    .not("sku", "is", null);

  if (error) {
    logActionFailure("products.generateSku.skuNamespaceLookup", error, {
      businessId: input.businessId,
      prefix: input.prefix
    });
    return { sku: null, error: "No pudimos generar el SKU automaticamente." };
  }

  const existingSkus = (data ?? []).map((row) => row.sku);
  return { sku: getNextAutoGeneratedProductSku(input.prefix, existingSkus) };
}

async function validateCategoryOwnership(input: {
  supabase: Awaited<ReturnType<typeof createSupabaseServerClient>>;
  businessId: string;
  categoryId: string;
}) {
  const { data, error } = await input.supabase
    .from("categories")
    .select("id")
    .eq("id", input.categoryId)
    .eq("business_id", input.businessId)
    .maybeSingle();

  if (error) {
    logActionFailure("products.validateCategoryOwnership", error, {
      businessId: input.businessId,
      categoryId: input.categoryId
    });
    return "No pudimos validar la categoria seleccionada.";
  }

  if (!data) {
    return "La categoria seleccionada no pertenece a tu negocio.";
  }

  return null;
}
